### ISSUE TITLE
Fails at selfcheck 

### ISSUE THREAD

**Issue by purplesun84** [ecmwf/eccodes-python#2]
Hi, I tried to install eccodes for python3  in my virtualenv today.
I had libeccodes0 installed before 
`i A libeccodes0                     - GRIB and BUFR enecoding/encoding software`

```
>> pip install git+https://github.com/ecmwf/eccodes-python
Collecting git+https://github.com/ecmwf/eccodes-python
  Cloning https://github.com/ecmwf/eccodes-python to /tmp/pip-req-build-lpa590qq
Collecting attrs (from eccodes-python==0.8.0)
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting cffi (from eccodes-python==0.8.0)
  Downloading https://files.pythonhosted.org/packages/a7/3f/2667a1516d935938245bd256b56a2f96d739ac3683e6778380f06c6e4c79/cffi-1.12.2-cp37-cp37m-manylinux1_x86_64.whl (430kB)
    100% |████████████████████████████████| 440kB 8.1MB/s 
Collecting numpy (from eccodes-python==0.8.0)
  Using cached https://files.pythonhosted.org/packages/91/e7/6c780e612d245cca62bc3ba8e263038f7c144a96a54f877f3714a0e8427e/numpy-1.16.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting pycparser (from cffi->eccodes-python==0.8.0)
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
    100% |████████████████████████████████| 163kB 47.4MB/s 
Building wheels for collected packages: eccodes-python, pycparser
  Building wheel for eccodes-python (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-uzfzt90s/wheels/c4/cf/53/3e513b6214aeacc46af40d3d9258aec5ab7f37107e982ee910
  Building wheel for pycparser (setup.py) ... done
  Stored in directory: /home/philipa8/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built eccodes-python pycparser
Installing collected packages: attrs, pycparser, cffi, numpy, eccodes-python
Successfully installed attrs-19.1.0 cffi-1.12.2 eccodes-python-0.8.0 numpy-1.16.2 pycparser-2.19
```
It says that its been installed: 
```
pip list
Package        Version
-------------- -------
attrs          19.1.0 
cdsapi         0.1.3  
cffi           1.12.2 
eccodes-python 0.8.0  
numpy          1.16.2 
pip            19.0.3 
pycparser      2.19   
setuptools     40.8.0 
wheel          0.33.1 

```

Unfortunately this didn't work:
``` 
python -m eccodes selfcheck
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/philipa8/Pyenvs/fe3/lib/python3.7/site-packages/eccodes/__init__.py", line 4, in <module>
    from .eccodes import *
  File "/home/philipa8/Pyenvs/fe3/lib/python3.7/site-packages/eccodes/eccodes.py", line 1, in <module>
    from gribapi import __version__
  File "/home/philipa8/Pyenvs/fe3/lib/python3.7/site-packages/gribapi/__init__.py", line 1, in <module>
    from .gribapi import *                # noqa
  File "/home/philipa8/Pyenvs/fe3/lib/python3.7/site-packages/gribapi/gribapi.py", line 26, in <module>
    from .bindings import ENC, ffi, lib
  File "/home/philipa8/Pyenvs/fe3/lib/python3.7/site-packages/gribapi/bindings.py", line 33, in <module>
    pkgutil.get_data(__name__, 'grib_api_prototypes.h').decode('utf-8') +
  File "/usr/lib/python3.7/pkgutil.py", line 637, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/philipa8/Pyenvs/fe3/lib/python3.7/site-packages/gribapi/grib_api.h'
```

**Comment by alexamici** [comment]
@purplesun84 thanks for your report! The specific problem should be fixed, now.

Please note that the code is pre-alpha and it is probably a bit early to trying it out, unless you are interested in helping with the development 😁
